# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - source
# 缓存，可以节省集成的时间
cache:
  npm: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "52admln"
- git config --global user.email "ismrwang@gmail.com"
- npm install -g parcel-bundler
install:
- git clone https://github.com/git-ftp/git-ftp.git
- cd git-ftp
- git checkout 1.1.0
- sudo make install
- npm i
script:
- npm run build
after_success:
- cd dist
- git init
- git add --all .
- git commit -m "Automatically update from travis-ci"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force "https://${REPO_TOKEN}@${REPO_URL}" master:master
- git ftp push --user ${user} --passwd ${sn} ftp://server-cn.52admin.net/public_html
